Разметка
htmlacademy-adaptive/1745893-cat-energy-1 pull request #2
Opened 2023-12-22 12:20 UTC by SerialEditor

2023-12-22 12:52 UTC, SerialEditor commented on source/index.html
> -        <dl class="result__stats metrics">
Андрей, генератор бэм-дерева декларирует проблему на уровне элементов блока metric, не могу разобраться, в чём проблема

2023-12-25 07:56 UTC, andreysgra requested changes
Кроме перечисленного ниже всё выполнено отлично.

2023-12-25 07:56 UTC, andreysgra commented on source/form.html
> +            <textarea class="customer-profile__input input" name="cat-habits"   id="cat-habits-comment">Расскажите обо всех повадках кота</textarea>
"Расскажите обо всех повадках кота" - а это не `placeholder`?

2023-12-25 07:56 UTC, andreysgra commented on source/catalog.html
> +        <button class="main-nav__toggle nav-menu-toggle">
Тип кнопки не указан.

2023-12-25 07:56 UTC, andreysgra commented on source/index.html
> +            <dd class="metric__value">15 000 руб.</dd>
![image](https://github.com/htmlacademy-adaptive/1745893-cat-energy-1/assets/17790771/4a44719d-8dc6-4490-b01f-7b9ce929d84e)
С буквой `c` в названии класса `metriс` проблемы, использована русская буква вместо латинской.

2023-12-25 16:47 UTC, SerialEditor commented on source/form.html
> +            <textarea class="customer-profile__input input" name="cat-habits"   id="cat-habits-comment">Расскажите обо всех повадках кота</textarea>
Э-х-х... Это именно он!

2023-12-25 17:07 UTC, SerialEditor commented on source/index.html
> +            <dd class="metric__value">15 000 руб.</dd>
![metric_section](https://github.com/htmlacademy-adaptive/1745893-cat-energy-1/assets/81110169/669feae2-c8e3-4169-9df1-c9c37dc8d1cc)
Только после того, как поменял клавиатуру)

2023-12-25 18:08 UTC, andreysgra commented on source/index.html
> -        <dl class="result__stats metrics">
Павел, у БЭМ блока `metric` вместо латинской `c` русская буква. У элементов буква правильная.

2023-12-25 18:10 UTC, merged